### PR TITLE
Support for Windows Hosts

### PR DESCRIPTION
**Pull request by mfradcourt**
ADD autoload the windows listener
ADD detect windows host and execute the proper listener
FIX frozen string error in windows listener
MOD error message for non supported OS

### CODE REVIEW

**Comment by smerrill** [comment]
Thanks for wiring this up!

I had a chance to run it through some quick tests and it looks like it's working well, so I'm going to merge it and I'm going to cut a new release sometime soon.

**Comment by mfradcourt** [comment]
Thanks to you for the amazing work !

**Comment by jamesj2** [comment]
Which build of windows rsync are you using?  I'm trying the cygwin version with no luck.

```
==> puppet: Doing an initial rsync...
==> puppet: Rsyncing folder: /cygdrive/c/Users/James/Documents/vagrant/boxes/puppet-server/src/etc/puppet/ => /shared/etc/puppet
==> puppet:   - Exclude: [".vagrant/", ".git/"]
==> cbizfile2: Doing an initial rsync...
==> cbizfile2: Rsyncing folder: /cygdrive/c/Users/James/Documents/vagrant/boxes/puppet-server/src/etc/puppet/ => /shared/etc/puppet

==> cbizfile2:   - Exclude: [".vagrant/", ".git/"]
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/synced_folders/rsync/helper.rb:149:in `rsync_single': There was an error when attempting to rsync a synced folder. (Vagrant::Errors::RSyncError)
Please inspect the error message below for more info.

Host path: /cygdrive/c/Users/James/Documents/vagrant/boxes/puppet-server/src/etc/puppet/
Guest path: /shared/etc/puppet
Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2201 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'C:/Users/James/Documents/vagrant/boxes/puppet-server/.vagrant/machines/cbizfile2/virtualbox/private_key' --exclude .vagrant/ --exclude .git/ /cygdrive/c/Users/James/Documents/vagrant/boxes/puppet-server/src/etc/puppet/ vagrant@127.0.0.1:/shared/etc/puppet
Error: Warning: Permanently added '[127.0.0.1]:2201' (RSA) to the list of known hosts.
sudo: rsync: command not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]
        from C:/Users/James/.vagrant.d/gems/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:50:in `block (2 levels) in execute'
        from C:/Users/James/.vagrant.d/gems/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:49:in `each'
        from C:/Users/James/.vagrant.d/gems/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:49:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
        from C:/Users/James/.vagrant.d/gems/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:38:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
        from C:/Users/James/.vagrant.d/gems/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/action/startup_rsync.rb:40:in `block in call'`
```

**Comment by mfradcourt** [comment]
Looking at this sudo: rsync: command not found
My guess is that you don't vagrant rsync in the box.

**Comment by jamesj2** [comment]
I do have rysnc installed.  I have been using a cygwin version of rsync with vagrant's stock rsync feature. 
```
> where rsync
C:\tools\cygwin\bin\rsync.exe
```

Gatling rsync now working for me.  I disabled gatling.latency and gatling.time_format in my Vagrantfile and did a vagrant reload and it worked.  So to check and make sure those settings caused the issues I re-enabled them and reloaded.  Hmm.. It still works.  Maybe it was just a fluke.

Thanks!

**Pull request merged**
